/* auto-generated by NAPI-RS */
/* eslint-disable */

export class ProtobufParser {
  constructor()
  parse(buffer: Buffer): string
  getSize(): number
  getData(): Buffer
}

export function decodeVarint(buffer: Buffer): number
export function encodeVarint(value: number): Buffer
export function decodeZigzag(value: number): number
export function encodeZigzag(value: number): number
export function decodeFieldTag(buffer: Buffer): Array<number>
export function encodeFieldTag(fieldNumber: number, wireType: number): Buffer
